### ISSUE TITLE
删除任务，任务上对应的工时未标记未删除

### ISSUE THREAD

**Issue by everpan** [easysoft/zentaopms#103]
删除任务，任务上对应的工时未标记未删除
或者提示，先删除工时再删除任务
或者提示，联动删除

**Comment by lanzongjun** [comment]
删除任务并不会删除相关日志

**Comment by everpan** [comment]
至少要标记下，工时统计的时候，就会多出工时。不便于工时分析

**Comment by xiaofeng993229** [comment]
“删除任务并不会删除相关日志”，这样设计的原因是，日志记录是已经某个已经发生的事件，它是真实发生过的。日志所属的任务被删除后，也不应该自动改变这个历史。
例如：张三为李四创建了个调用市场任务，李四为此任务付出了3天的工时，但是后面这个市场任务被任务是不合理的，需要将任务删除，但是不能改变李四为这个任务付出了3天工时。
