### ISSUE TITLE
Bug中包含视频文件，不能直接查看，非常不方便

### ISSUE THREAD

**Issue by hztony** [easysoft/zentaopms#105]
很多 App 上的 bug，为了加强 bug 步骤的可靠性，一般采用录制小视频方式上传禅道，但是开发人员在查看这些 bug 时候，需要下载视频才能看到，这样就非常不方便，而且还要手动去删除下载后的视频，希望能改进下，可以直接观看，这样可以增加开发人员的操作便捷性，提升开发人员对禅道的认可性。

**Comment by sy-records** [comment]
感谢您的反馈。这个目前已经纳入2023年的产品规划中进行增强，敬请期待。

**Comment by xiaofeng993229** [comment]
已记录反馈 （PMS 6330）
