### ISSUE TITLE
There is a SQL injection in the product. (项目中存在sql注入问题)

### ISSUE THREAD

**Issue by l3s10n** [easysoft/zentaopms#106]
![image](https://user-images.githubusercontent.com/72327909/205977751-4dd4ea24-986d-4a70-80ed-a375bc24ac9c.png)
执行一个创建数据库test的sql语句：
![image](https://user-images.githubusercontent.com/72327909/205977820-85c496f3-d200-4912-99cb-53b8b0a51963.png)

**Comment by ysicing** [comment]
参考 https://github.com/l3s10n/ZenTaoPMS_SqlInjection

**Comment by sy-records** [comment]
Thank you for your feedback. @l3s10n

**Comment by sy-records** [comment]
Low version users can download patch. https://www.zentao.net/extension-browseRelease-6-front.html
