### ISSUE TITLE
17.7 update to 18.0报错

### ISSUE THREAD

**Issue by everpan** [easysoft/zentaopms#107]
13:51:41 Uncaught Error: Undefined constant "TABLE_IM_CHATUSER" in module/upgrade/model.php:8013
Stack trace:
#0 module/upgrade/model.php(576): upgradeModel->xuanSetMuteForHiddenGroups()
#1 module/upgrade/model.php(103): upgradeModel->executeOpen('17_8', 'open', false, '17_7')
#2 module/upgrade/control.php(150): upgradeModel->execute('17_7')
#3 framework/base/router.class.php(2199): upgrade->execute('17_7')
#4 www/upgrade.php(83): baseRouter->loadModule()
#5 {main}
thrown in module/upgrade/model.php on line 8013 when visiting /zentao/www/upgrade.php?m=upgrade&f=execute

**Comment by sy-records** [comment]
没复现，可以检查下你目录中是否存在`config/ext/_0_xuanxuan.php`文件

**Comment by everpan** [comment]
不存在该文件

drwxr-xr-x  10 ever  admin    320 12 29 11:34 .
drwxr-xr-x  18 ever  admin    576 12 29 13:49 ..
-rw-r--r--   1 ever  admin  12775 12 29 13:47 config.php
-rwxr-xr-x   1 ever  admin  22121 12 29 13:47 filter.php
-rw-r--r--   1 ever  admin      0 12 29 13:47 index.html
drwxr-xr-x   4 ever  admin    128 12 29 11:23 license
-rw-r--r--   1 ever  admin    652 12 29 13:46 my.php
-rw-r--r--   1 ever  admin   6335 12 29 13:47 routes.php
-rw-r--r--   1 ever  admin   8267 12 29 13:47 timezones.php
-rw-r--r--   1 ever  admin  22226 12 29 13:47 zentaopms.php

**Comment by sy-records** [comment]
那你丢文件了，或者你是从GitHub自己构建的，请从官网下载压缩包 https://www.zentao.net/download.html

**Comment by everpan** [comment]
尝试ok 多谢
