### ISSUE TITLE
能不能在项目流程加上代码评审流程环节

### ISSUE THREAD

**Issue by dpjs** [easysoft/zentaopms#108]
代码评审环节包括代码评审计划、代码审查缺陷库、评审报告

**Comment by xiaofeng993229** [comment]
您好。
禅道在项目中没有集成代码评审的环节。

您可以了解下禅道的 Devops 功能。
它实现了对接gitlab,gitea,gogs,svn 等代码托管平台，源代码在禅道中可预览、跨版本对比，可以针对某一行代码提出问题，并指派给相应人人员跟进。
同时还实现了对接 sonarqube，可以执行某个代码仓库的扫描，获取代码扫描的报告。
