### ISSUE TITLE
关于调用API进行二次开发的问题

### ISSUE THREAD

**Issue by wang-xiaowu** [easysoft/zentaopms#109]
1、访问 http://x.com/api-getsessionid.json获取禅道session信息
2、使用上一步获取的session作为url参数访问 http://x.com/user-login.json?account=account&password=123456&zentaosid=6v9bl9hp3o5chvdd46u5fg36g4
3、http://x.com/project-index-no.json?zentaosid=6v9bl9hp3o5chvdd46u5fg36g4

我按照如上方式调用api，第三步无论调用哪个接口都是返回这样的字符串

```
{"status":"success","data":"{\"locate\":\"http:\\\/\\\/localhost:9999\\\/user-login-L3VzZXItcHJvZmlsZS0wMDEuanNvbj90aWQ9MDRkNzU3c3E=.json?tid=04d757sq\"}","md5":"4efcdb5be27bdbc23ed8a7e6657f2f77"}
```

**Comment by sy-records** [comment]
请通过文档提供的API方式进行操作：https://www.zentao.net/book/api/664.html

**Comment by wang-xiaowu** [comment]
> 请通过文档提供的API方式进行操作：https://www.zentao.net/book/api/664.html

```
[root@VM-30-197-centos 80]# curl --location --request POST 'http://localhost:9999/tokens' --header 'Content-Type: application/json' --data '{
    "account": "admin",
    "password": "123456"
}'
```
请求格式如上，没有正常返回response

![chrome-capture-2023-2-18](https://user-images.githubusercontent.com/44340137/226099595-4708c8d1-04df-4b35-a232-91c32ec7032f.gif)

**Comment by sy-records** [comment]
path不对，/api.php/v1/tokens
