### ISSUE TITLE
调用API进行创建bug的时候，无法指定指派人

### ISSUE THREAD

**Issue by wang-xiaowu** [easysoft/zentaopms#110]
![image](https://user-images.githubusercontent.com/44340137/227156784-97c32f9d-3c75-46a7-adf6-7accd3446051.png)

![image](https://user-images.githubusercontent.com/44340137/227156887-bf23ee94-8d0b-444d-a665-716238b1de50.png)

**Comment by wang-xiaowu** [comment]
执行api创建bug的时候，可以指定指派人么？

**Comment by sy-records** [comment]
`assignedTo` 类型是`string`，传入`account`的值
