### ISSUE TITLE
禅道18.3源码安装到第4步时无法继续

### ISSUE THREAD

**Issue by royqh1979** [easysoft/zentaopms#111]
禅道18.3源码安装，在执行到第4步时点击“使用轻量管理模式”或“使用全生命周期管理模式”按钮均无响应：
![image](https://user-images.githubusercontent.com/8803140/229327191-b6f8d7b8-4a76-46b3-a29f-2d9c1540bd1b.png)

chrome开发者工具的控制台提示如下错误:
GEThttp://localhost/zentaopms/www/theme/default/en.default.css?v=18.3
[HTTP/1.1 404 Not Found 0ms]

GEThttp://localhost/zentaopms/www/js/all.js?v=18.3
[HTTP/1.1 404 Not Found 0ms]

指向“http://localhost/zentaopms/www/js/all.js?v=18.3”的 <script> 加载失败。 install.php:14:1
Uncaught ReferenceError: jQuery is not defined
    <anonymous> jQuery
min.js:2:3
Uncaught ReferenceError: $ is not defined
    <anonymous> http://localhost/zentaopms/www/install.php?m=install&f=step4:182

**Comment by sy-records** [comment]
自己从源码安装时，到这一步的时候需要修改config/my.php中debug为true，然后刷新这个页面重新选择页面即可。
