### ISSUE TITLE
打开插件管理报错

### ISSUE THREAD

**Issue by ashangpeng** [easysoft/zentaopms#113]
09:15:06 Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in module/common/model.php:897
Stack trace:
#0 module/common/model.php(897): method_exists()
#1 module/common/view/header.html.php(15): commonModel::printHomeButton()
#2 module/extension/view/safe.html.php(13): include('...')
#3 framework/control.class.php(385): include('...')
#4 framework/base/control.class.php(662): control->parseDefault()
#5 framework/base/control.class.php(917): baseControl->parse()
#6 module/extension/control.php(35): baseControl->display()
#7 framework/base/router.class.php(1497): extension->__construct()
#8 www/index.php(71): baseRouter->setParams()
#9 {main}
thrown in module/common/model.php on line 897 when visiting /index.php?m=extension&f=browse

**Comment by sy-records** [comment]
使用的哪个版本？

**Comment by sy-records** [comment]
Fixed via 2bcbd468
