### ISSUE TITLE
开源版本是否支持角色列表和部门列表的获取

### ISSUE THREAD

**Issue by hzjsea** [easysoft/zentaopms#115]

**Comment by hzjsea** [comment]
根据文档来说，可以通过http://193.5.100.21:8000/api.php/v1/users/:id设置用户的基本信息，
但是没有找到对应的角色列表和部门列表获取的接口， 是需要升级到付费版本吗？
有没有几个版本之间可调用API接口差异的详细对比文档


当前参考文档  文档---接口库中的restful风格的文档
![图片](https://user-images.githubusercontent.com/61597549/234817958-e263e01b-097f-4084-9bab-572d31ef4bc8.png)

**Comment by sy-records** [comment]
这里还没有提供接口，如果目前需要，可以通过二次开发实现

**Comment by xiaofeng993229** [comment]
如果需要二次开发可以添加技术支持的qq  1945249968， 邀请您加入二次开发交流群，在群里您会得到更及时的答复。
