### ISSUE TITLE
禅道BUG新增的时候，所属执行没有把已关闭的过滤掉

### ISSUE THREAD

**Issue by yangjourney** [easysoft/zentaopms#116]
禅道BUG新增的时候，所属执行没有把已关闭的过滤掉
应该参考影响版本，默认展示可用的，点击所有能加载全部~

**Comment by sy-records** [comment]
需要自己设置条件，后台设置了关闭执行禁止操作的话才会选不到，不然就是正常可以选择得到

![image](https://github.com/easysoft/zentaopms/assets/33931153/e6551cef-eb30-4a39-8604-e487d353f715)
