### ISSUE TITLE
禅道【18.3】添加钉钉 Webhook，一直提示 没有选择部门，请先选择同步部门。

### ISSUE THREAD

**Issue by nowyouseeit** [easysoft/zentaopms#117]
1. 禅道有添加部门信息，并创建对应人员
2. 钉钉创建应用是管理员，有对应权限
3. 钉钉应用授权全部【通讯录】权限

![image](https://user-images.githubusercontent.com/31727621/235105931-918b6139-53b6-48d7-b377-7ca8e1d8d37e.png)
![image](https://user-images.githubusercontent.com/31727621/235106311-8220f6b2-14c9-4ca6-94eb-3c3298d42fcc.png)
![image](https://user-images.githubusercontent.com/31727621/235106098-e9ba8077-ecf7-4dad-8f12-bf7efe300d47.png)

**Comment by sy-records** [comment]
可以查看下`tmp/log/saas-*`的日志，钉钉api的响应是什么。

<img width="943" alt="image" src="https://user-images.githubusercontent.com/33931153/236361733-3f985197-31ef-4352-9a2a-9ba07a191307.png">
