### ISSUE TITLE
Can zentao bootstrapping?

### ISSUE THREAD

**Issue by xiaoyao9184** [easysoft/zentaopms#12]
As a potential user, I would like to know whether zentao has been through the zentao management of the new version of zentao.

If implemented, where can I find, real inside [demo](Http://demo.zentao.pm/project-all-undone-1.html) ?

If not implemented, then why. 
Hosted in Github did not close the Issue system, because the Issue system is better than zentao, or because zentao has not yet reached the point of maturity?

**Comment by easysoft** [comment]
你觉得我们会做这种事情吗？我们本身是做项目管理软件，我们自己的项目管理不用禅道管理？那岂不是让人笑话。我们从最开始版本的项目管理到今天正在进行中的项目，都可以公开看到：http://pms.zentao.net
我们官网上面也都有相应的链接。
至于github上面的issue，多一个反馈的途径有什么不好？
