### ISSUE TITLE
文档查看页面加载特别长

### ISSUE THREAD

**Issue by ganl** [easysoft/zentaopms#126]
版本18.7

![image](https://github.com/easysoft/zentaopms/assets/11937688/b0cdcb03-6dbb-4c77-aa34-48f59e3a9491)

修改 进入速度正常

**Comment by sy-records** [comment]
蓝色部分是`Content Download`流程，可能需要根据实际的内容、服务器配置等做判断进行优化。

**Comment by xiaofeng993229** [comment]
另外有一种可能是这个文档被修改的次数比较多。
在文档查看的页面会一次性的将所有的编辑记录加载到页面上。有可能造成一个现象，文档本身不大，但是请求的数据量非常大，加载的速度也非常慢。

您如果满足以上的操作路径，可以尝试将之前的文档归档，再创建一个全新的文档，页面加载慢的问题就能解决。

另外我们已将该操作路径的问题提交给了产品同事 （反馈6329）。
