### ISSUE TITLE
我是专业版用户，希望有个好的渠道反馈用户的需求

### ISSUE THREAD

**Issue by wanjochan** [easysoft/zentaopms#13]
我是专业版用户，希望有个好的渠道反映用户的需求（并不是说要求做，只是反馈供参考哦）
pms.zentao.net只有游客身份，在这里反映issue好像又不太合适

**Comment by easysoft** [comment]
可以到我们网站论坛。http://www.zentao.net/forum/feedback.html
也可以加我们QQ群。请联系徐贺：1492153927，他会邀请你加群。
