### ISSUE TITLE
docker-compose方式启动失败

### ISSUE THREAD

**Issue by 100ZZ** [easysoft/zentaopms#130]
### 描述 (Description)

docker-compose.yml文件如下（基本和官网类似，就改了PORT)：
`version: '3.0'

services:
# mysql service for zentao
  zentao-mysql:
    image: bitnami/mysql:8.0
    container_name: zentao-mysql
    ports:
      - '13306:3306'
    volumes:
      - /data/zentao/db:/bitnami/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=pass4Zentao
      - MYSQL_DATABASE=zentao
    networks:
      - zentao-net
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mysql/healthcheck.sh']
      interval: 15s
      timeout: 5s
      retries: 6

# zentao service
  zentao:
    image: hub.zentao.net/app/zentao
    container_name: zentao
    ports:
      - '10080:80'
    volumes:
      - /data/zentao/file:/data
    depends_on:
      - zentao-mysql
    environment:
      - ZT_MYSQL_HOST=zentao-mysql
      - ZT_MYSQL_PORT=3306
      - ZT_MYSQL_USER=root
      - ZT_MYSQL_PASSWORD=pass4Zentao
      - ZT_MYSQL_DB=zentao
      - PHP_MAX_EXECUTION_TIME=120
      - PHP_MEMORY_LIMIT=512M
      - PHP_POST_MAX_SIZE=128M
      - PHP_UPLOAD_MAX_FILESIZE=128M
      - LDAP_ENABLED=false
      - SMTP_ENABLED=false
      - APP_DEFAULT_PORT=80
      - APP_DOMAIN=zentao.demo.com
      - PROTOCOL_TYPE=http
      - IS_CONTAINER=true
      - LINK_GIT=false
      - LINK_CI=false
    networks:
      - zentao-net

networks:
  zentao-net:
    driver: bridge`

### 期望 (Expectation)

能够正常启动

### 结果 (Result)

`
    Name                  Command               State                    Ports
-----------------------------------------------------------------------------------------------
zentao         /usr/bin/entrypoint.sh           Up       0.0.0.0:10080->80/tcp,:::10080->80/tcp
zentao-mysql   /opt/bitnami/scripts/mysql ...   Exit 1
# docker-compose logs -f zentao
Attaching to zentao
zentao          |  09:39:06.26
zentao          |  09:39:06.26 Welcome to the Easysoft ZenTao 18.9 container
zentao          |  09:39:06.26 Subscribe to project updates by watching https://www.zentao.net
zentao          |  09:39:06.26 Submit issues and feature requests at https://www.zentao.net/ask.html
zentao          |  09:39:06.26
zentao          |  09:39:06.27 INFO  ==> Prepare persistence directories.
zentao          |  09:39:06.50 INFO  ==> Render php.ini with environment variables.
zentao          |  09:39:06.51 INFO  ==> Check zentao data owner...
zentao          |  09:39:06.51 INFO  ==> Render apache sites config with envionment variables.
zentao          |  09:39:06.52 INFO  ==> Prepare custom extensions.
zentao          |  09:39:06.54 INFO  ==> Check whether the MySQL is available.
zentao          |  09:39:06.55 INFO  ==> Check whether the Apache is available.
zentao          |  09:39:07.55 WARN  ==> Sentry: Waiting Apache 1 seconds
zentao          |  09:39:07.77 WARN  ==> Apache: Waiting MySQL 1 seconds
zentao          |  09:39:09.56 WARN  ==> Sentry: Waiting Apache 2 seconds
zentao          |  09:39:09.93 WARN  ==> Apache: Waiting MySQL 2 seconds
zentao          |  09:39:13.56 WARN  ==> Sentry: Waiting Apache 4 seconds
zentao          |  09:39:14.11 WARN  ==> Apache: Waiting MySQL 4 seconds
zentao          |  09:39:21.57 WARN  ==> Sentry: Waiting Apache 8 seconds
zentao          |  09:39:22.26 WARN  ==> Apache: Waiting MySQL 8 seconds
zentao          |  09:39:37.58 WARN  ==> Sentry: Waiting Apache 16 seconds
zentao          |  09:39:42.47 WARN  ==> Apache: Waiting MySQL 16 seconds
zentao          |  09:40:09.58 WARN  ==> Sentry: Waiting Apache 32 seconds
zentao          |  09:40:09.59 ERROR ==> Sentry Maximum number of retries reached!
zentao          |  09:40:09.59 ERROR ==> Sentry Unable to connect to Apache: 127.0.0.1:80
zentao          | s6-supervise 03-roadrunner: warning: finish script lifetime reached maximum value - sending it a SIGKILL`

**Comment by 100ZZ** [comment]
二进制和docker方式貌似没问题

**Comment by 100ZZ** [comment]
行吧，我的锅改了下compose文件，应该OK
`zentao          |  14:35:17.46 INFO  ==> Go to http://<host IP>[:port] to complete the installation wizard
zentao          |  14:35:17.46 INFO  ==> 访问http://<宿主机IP>[:端口] 完成安装向导
zentao          |  14:35:20.47 INFO  ==> Go to http://<host IP>[:port] to complete the installation wizard
zentao          |  14:35:20.47 INFO  ==> 访问http://<宿主机IP>[:端口] 完成安装向导
zentao          |  14:35:25.48 INFO  ==> Go to http://<host IP>[:port] to complete the installation wizard
zentao          |  14:35:25.48 INFO  ==> 访问http://<宿主机IP>[:端口] 完成安装向导
zentao          |  14:35:30.49 INFO  ==> Go to http://<host IP>[:port] to complete the installation wizard
zentao          |  14:35:30.49 INFO  ==> 访问http://<宿主机IP>[:端口] 完成安装向导`

**Comment by ferrymo** [comment]
> 行吧，我的锅改了下compose文件，应该OK zentao | 14:35:17.46 INFO ==> Go to http://[:port] to complete the installation wizard zentao | 14:35:17.46 INFO ==> 访问http://<宿主机IP>[:端口] 完成安装向导 zentao | 14:35:20.47 INFO ==> Go to http://[:port] to complete the installation wizard zentao | 14:35:20.47 INFO ==> 访问http://<宿主机IP>[:端口] 完成安装向导 zentao | 14:35:25.48 INFO ==> Go to http://[:port] to complete the installation wizard zentao | 14:35:25.48 INFO ==> 访问http://<宿主机IP>[:端口] 完成安装向导 zentao | 14:35:30.49 INFO ==> Go to http://[:port] to complete the installation wizard zentao | 14:35:30.49 INFO ==> 访问http://<宿主机IP>[:端口] 完成安装向导

老哥，你该的哪里
