### ISSUE TITLE
禅道看板项目任务显示异常

### ISSUE THREAD

**Issue by dpjs** [easysoft/zentaopms#131]
### 描述 (Description)

**看板项目创建任务后不显示任务相关信息，也无法进行编辑和任务开始等节点处理**
![image](https://github.com/easysoft/zentaopms/assets/19635623/b5f354e7-9dc6-4ee6-8243-f94807393339)

### 期望 (Expectation)

显示项目名称等信息，可以进行编辑和任务节点处理

### 结果 (Result)

无法显示任务名称信息，也无法进行编辑，也无法进行任务开始和完成等节点操作

### 软件版本 (Software version)

18.10

**Comment by sy-records** [comment]
此处应该是设计如此，如果你要看完整的信息，可以改成1个。

<img width="442" alt="image" src="https://github.com/easysoft/zentaopms/assets/33931153/3897573f-2a62-4024-9076-4444c753d480">
