### ISSUE TITLE
工时不能自动扣除

### ISSUE THREAD

**Issue by lmj-hub** [easysoft/zentaopms#132]
### 描述 (Description)

为什么填工时的时候不能自动扣工时，要自己一个一个手动地计算呢？一不小心还会算错，这个功能用户体验感极差。

### 期望 (Expectation)

填入当天工时后，能够自动计算出剩余工时，而不是需要用户手动计算剩余工时

### 结果 (Result)

目前填入当天工时后，需要用户手动计算剩余工时

**Comment by sy-records** [comment]
该功能目前没有计划支持，可以关注后续动态。

----

可以通过扩展js或者油猴脚本的写法来自行实现。

**Comment by wwccss** [comment]
因为剩余工时不是简单的等于预计工时减去消耗工时。这个功能做起来很简单，但这样做从管理角度来讲是不严谨的。

**Comment by lmj-hub** [comment]
从管理者的角度是不严谨 是什么意思吗？

---- 回复的原邮件 ----
| 发件人 | chunsheng ***@***.***> |
| 发送日期 | 2024年07月10日 08:55 |
| 收件人 | easysoft/zentaopms ***@***.***> |
| 抄送人 | lmj-hub ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [easysoft/zentaopms] 工时不能自动扣除 (Issue #132) |

因为剩余工时不是简单的等于预计工时减去消耗工时。这个功能做起来很简单，但这样做从管理角度来讲是不严谨的。

**Comment by wwccss** [comment]
禅道作为一个通用的管理工具，我们不能在里面内置这样的逻辑，会对用户造成误导。
我们设计的初衷是希望用户在更新工时的时候能够对任务进行再次的估算。
你们如果有这样需求的话，可以自己改一下表单的逻辑。
