### ISSUE TITLE
There is a remote command execution vulnerability after login（存在后台远程命令执行漏洞）

### ISSUE THREAD

**Issue by l3s10n** [easysoft/zentaopms#133]
### 描述 (Description)

详情见：“https://github.com/l3s10n/ZenTaoPMS_RCE”

### 期望 (Expectation)

修复漏洞

### 结果 (Result)

后台命令执行

### 软件版本 (Software version)

18.0 - 18.10

**Comment by fireware** [comment]
新版本已修复，建议升级到 18.12 版本，[点击下载](https://www.zentao.net/download/zentaopms18.12-83589.html)
