### ISSUE TITLE
禅道15.8webhook接入飞书消息通知，支持自定义消息模板吗？

### ISSUE THREAD

**Issue by mx94** [easysoft/zentaopms#134]
### 描述 (Description)

想自定义消息模板，比如飞书的markdown类型，需要怎么配置呀？
如果不能配置，可以自己二次开发一个webhook接口不

### 期望 (Expectation)

![image](https://github.com/easysoft/zentaopms/assets/20527751/7e112d91-9907-4e92-92c4-d3fe8da7a0c7)

### 结果 (Result)

![image](https://github.com/easysoft/zentaopms/assets/20527751/4c04205c-e2d6-4445-b8ca-7557da78151b)

### 软件版本 (Software version)

15.8

**Comment by sy-records** [comment]
不支持自定义消息模板，但是你可以自己二开，或者修改下源码，可以参考 https://github.com/easysoft/zentaopms/commit/37445a4968bc3519ebf10c72c3e28c19bfebb4fe
