### ISSUE TITLE
抱歉没找到关于Q&A的地方，想请问下下关于17.6降级到16有没有什么特别需要注意的

### ISSUE THREAD

**Issue by wang-xiaowu** [easysoft/zentaopms#135]
### 描述 (Description)

因为个人原因想把zentao【Docker开源版】从17降级到16，不知道是否可以直接兼容

### 期望 (Expectation)

zentao【Docker开源版】成功从17降级到16

### 结果 (Result)

Q&A

### 软件版本 (Software version)

17.6

**Comment by sy-records** [comment]
https://www.zentao.net/ask.html
