### ISSUE TITLE
docker 安装 20.0.beta2 

### ISSUE THREAD

**Issue by rola0411** [easysoft/zentaopms#136]
### 描述 (Description)

20.0.beta2 到初始化页面到数据库那一步，点击下一步没反应。
使用的是外部mysql8.0.36版本

### 期望 (Expectation)

![image](https://github.com/easysoft/zentaopms/assets/46880610/ccdb9026-d95d-4857-a078-aee5e743b7f1)

### 结果 (Result)

![image](https://github.com/easysoft/zentaopms/assets/46880610/e843b0b7-7f4a-4638-9078-a2fa6bd43435)

**Comment by sy-records** [comment]
自己从repo构建的还是使用官方提供的镜像？
