### ISSUE TITLE
执行一条案例在回到点测试单就报错

### ISSUE THREAD

**Issue by kinbod** [easysoft/zentaopms#139]
### 描述 (Description)

执行一条案例在回到点测试单就报错

### 期望 (Expectation)

正常展示列表

### 结果 (Result)

![027e1c33cf054fdc7bae2ff661b4b684](https://github.com/easysoft/zentaopms/assets/8268021/0e64b607-2be4-465c-9806-4ebc8c80dcc7)

### 软件版本 (Software version)

20.0

**Comment by kinbod** [comment]
这个问题主要出现在，设置了分页数量的时候，比如把默认每页显示20条修改成500或者1000的时候，然后查看用例，然后再点击查看测试单点击里面的测试单名称然后就报错了

**Comment by sy-records** [comment]
Duplicate of #140 

see https://github.com/easysoft/zentaopms/issues/140#issuecomment-2141712208
