### ISSUE TITLE
重新设置公司名后每日提醒邮件的title还是老的名字

### ISSUE THREAD

**Issue by jhipster-china** [easysoft/zentaopms#14]
举例：原公司名称是：“公司A”

即使之后修改了公司名称为：“公司B”

在邮件提醒中显示的公司名还是 “公司A”，但是指派任务发送的邮件显示的是新公司“公司B”

估计：是初始化项目设置公司的时候有配置文件记录了公司A，每日提醒邮件使用的是配置文件

**Comment by easysoft** [comment]
退出，重新登录。

**Comment by jhipster-china** [comment]
退出重新登入没用的，最终解决是重启server，说明邮件通知里的变量是重启时读的，修改公司名称不会更新，这是个bug，请 reopen

**Comment by easysoft** [comment]
每日提醒应该是用后台的计划任务异步发的。那个是一个常驻进程，相当于没有退出。你重启webserver相当于退出重新启动了一个进程。先记下了。
