### ISSUE TITLE
页面点击报错

### ISSUE THREAD

**Issue by kinbod** [easysoft/zentaopms#140]
### 描述 (Description)

设置页面显示条数后，出现报错

### 期望 (Expectation)

正常显示

### 结果 (Result)

![c5293dda639808dce5421e81545cc2b](https://github.com/easysoft/zentaopms/assets/8268021/ef1779d5-34ef-4205-82bc-16ecdacb96b9)

### 软件版本 (Software version)

20.0

**Comment by kinbod** [comment]
这个错误频率很高

**Comment by fireware** [comment]
$moduleID = ($browseType == 'bymodule') ? $param : ($browseType == 'bysearch' ? 0 : ($this->cookie->taskCaseModule ?: 0))

**Comment by fireware** [comment]
已收到问题，将会在下个版本修复。应急方案：找到 `zentaopms/module/testtask/control.php` 第 401 行，将 `$this->cookie->taskCaseModule` 强转为 `int`，修改后的代码如下：

**Comment by kinbod** [comment]
就是这里的问题

**Comment by sy-records** [comment]
Fixed via 9667d698
