### ISSUE TITLE
项目编辑项目负责人后，任务无法选团队其他人员

### ISSUE THREAD

**Issue by dpjs** [easysoft/zentaopms#145]
### 描述 (Description)

1、创建无迭代项目型项目，编辑项目负责人为其他人员，创建任务无法选择项目团队中其他人员
![image](https://github.com/easysoft/zentaopms/assets/19635623/f40d3546-cdcd-4936-a39b-bfb0cc4151bc)
![image](https://github.com/easysoft/zentaopms/assets/19635623/96264aa6-960e-4de4-8b82-4539a7e89175)
只能选择这两个人，无法选到其它人
![image](https://github.com/easysoft/zentaopms/assets/19635623/8157e966-9e58-4fac-a564-ab8eba863ce2)

### 期望 (Expectation)

更改项目负责人，能正常进行项目任务创建

### 结果 (Result)

项目任务无法选择团队其它人员

### 软件版本 (Software version)

20.1.1

**Comment by sy-records** [comment]
已创建内部反馈：PMS-6128

**Comment by xiaofeng993229** [comment]
该问题 已于20.3 版本修复。
