### ISSUE TITLE
禅道20.1.1版本，是否可以支持对接OIDC Provider，并提供SSO功能呢？

### ISSUE THREAD

**Issue by tedyage** [easysoft/zentaopms#147]
我接到一个客户需求，要禅道对接他们的IAM系统实现SSO，其客户要使用最新版禅道。
我看目前最新的禅道社区版是20.1.1版本。
请问这个版本的禅道是否可以支持对接OIDC，并提供SSO功能呢？

**Comment by sy-records** [comment]
已创建内部反馈：PMS-6355

**Comment by sy-records** [comment]
可以试试 https://www.zentao.net/extension-viewExt-284.html

**Comment by tedyage** [comment]
这个插件不符合我们的需求。
这个插件提供的是让禅道拥有OIDC服务端的功能。
而我们的需求，是让禅道进作为OIDC的客户端，去对接其它的OIDC服务端。

**Comment by sy-records** [comment]
那这个需要定制开发了，集成自己的SSO，目前有集成GitHub、GitLab、Gitee、钉钉、飞书、企业微信、QQ和禅道的插件。
