### ISSUE TITLE
多人并行任务添加人员点击保存按钮无反应

### ISSUE THREAD

**Issue by dpjs** [easysoft/zentaopms#148]
### 描述 (Description)

项目任务视图，创建任务，选择多人并行任务，添加人员点击保存按钮无效，刷新浏览器后可以正常添加人员
![image](https://github.com/user-attachments/assets/1b6a1960-88bf-47f5-bb9f-eb66786c04df)

### 期望 (Expectation)

可以正常添加人员

### 结果 (Result)

必须要刷新后才能添加人员，从项目任务进去添加保存无反应

### 软件版本 (Software version)

20.3.0

**Comment by xiaofeng993229** [comment]
请使用admin用户，登录禅道，在后台-插件管理-本地安装，上传下附件中的f6589.zip补丁包。
该附件修复次问题。 
[f6589.zip](https://github.com/user-attachments/files/16606933/f6589.zip)
