### ISSUE TITLE
需求详情页中建任务，跳转页面错误

### ISSUE THREAD

**Issue by dpjs** [easysoft/zentaopms#149]
### 描述 (Description)

项目需求空间，点击某一条需求进入需求详情，点击创建任务跳转到创建执行页面
![image](https://github.com/user-attachments/assets/fae19466-dc0b-4afa-ad2e-e987cd607e25)

### 期望 (Expectation)

跳转到创建任务页面

### 结果 (Result)

目前都是跳转到创建执行页面

### 软件版本 (Software version)

20.3.0

**Comment by xiaofeng993229** [comment]
谢谢反馈，已记录问题（反馈id：6303），正常如果项目启用了迭代，在项目的研发需求详情页面是不应该有建任务按钮的。任务都是在项目的迭代下进行管理的，应该先在项目下创建迭代，将需求关联到迭代后，对迭代中的需求创建任务

**Comment by xiaofeng993229** [comment]
问题已在 [20.5](https://www.zentao.net/download/pms20.5.stable-84179.html) 版本解决。
解决方案：启用迭代的项目下，需求详情不显示建任务，无迭代项目下才显示。
