### ISSUE TITLE
Visible details of the previous session

### ISSUE THREAD

**Issue by Abhinavram** [easysoft/zentaopms#15]
After logging out, I clicked the back button on the browser and all the details were visible. 
![image](https://user-images.githubusercontent.com/15023872/32633662-0960903e-c56e-11e7-891c-10d89c5ef40b.png)
We would actually expect to be redirected back to login page.

**Comment by fireware** [comment]
The page is loaded from the cache of browser. You click any link it will redirect to the login page.

**Comment by Abhinavram** [comment]
I tried this in incognito mode, however the details were still visible.

**Comment by easysoft** [comment]
1. When you back the browser by click the back button, what's you see is the cache.
2. If you enable the guest user, disable it. Because if you enable the guest user, anyone can see pages without loging into zentao.
