### ISSUE TITLE
多人并行任务编辑任务内容后，原任务人员没有了

### ISSUE THREAD

**Issue by dpjs** [easysoft/zentaopms#150]
### 描述 (Description)

项目空间创建任务，选择多人并行任务保存，再次编辑任务描述内容后保存，任务团队人员信息没有了
![image](https://github.com/user-attachments/assets/0ae96674-6d70-42da-be6f-93fc8a49cdcb)
![image](https://github.com/user-attachments/assets/d81a782a-0eab-44a1-8386-7039dc8f3f5f)

### 期望 (Expectation)

任务编辑对任务团队人员数据无影响

### 结果 (Result)

目前任务重新编辑后团队成员没有了

### 软件版本 (Software version)

20.3.0

**Comment by xiaofeng993229** [comment]
登录禅道数据库，修改下zt_taskteam表中order字段为mediumint(8)，重新编辑下，看是否正常。
