### ISSUE TITLE
编辑【指派给我的bug】弹窗，每编辑一次，后面的“指派给我”文案就会被增加一次

### ISSUE THREAD

**Issue by Realzzz1874** [easysoft/zentaopms#151]
### 描述 (Description)

编辑【指派给我的bug】弹窗，每编辑一次，后面的“指派给我”文案就会被增加一次
<img width="876" alt="image" src="https://github.com/user-attachments/assets/79d2b606-5225-424e-8184-c5826dabfd30">
<img width="933" alt="image" src="https://github.com/user-attachments/assets/e1ec4b80-0a26-4593-87d1-60d401767080">

### 期望 (Expectation)

文案被正确设置

### 结果 (Result)

文案设置失败

**Comment by xiaofeng993229** [comment]
你是在哪个版本发现的该问题 ？
我在最新版本20.4没有重新该问题。如果你不是最新版本，可以升级到最新。

另外我们目前主要的问题收集渠道是我们的[官网论坛](https://www.zentao.net/forum.html)和[问答](https://www.zentao.net/ask.html) ，后面可以在这里交流。
