### ISSUE TITLE
多人并行任务重新指派人员，原先已经启动的人员状态又变成未开始

### ISSUE THREAD

**Issue by dpjs** [easysoft/zentaopms#152]
### 描述 (Description)

重新指派人员，点击保存，之前已经启动的人员任务状态又变成未开始
![image](https://github.com/user-attachments/assets/c4ba9ce0-0724-4410-821f-57f448cb5022)

### 期望 (Expectation)

之前人员状态保持不变

### 结果 (Result)

已经启动的状态变成了未开始

### 软件版本 (Software version)

20.3.0

**Comment by xiaofeng993229** [comment]
感谢您的反馈，该问题已记录（id:6746）

**Comment by xiaofeng993229** [comment]
该问题已在21.0 版本中修复。
