### ISSUE TITLE
ERROR: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'storyTitle' in order clause is ambiguous 

### ISSUE THREAD

**Issue by xujuchao** [easysoft/zentaopms#153]
### 描述 (Description)

执行--->研发，在基于任务需求筛选的时候直接报SQL操作

18:47:45 #0 lib/base/dao/dao.class.php(1652): baseRouter->triggerError('SQLSTATE[23000]...', 'li...', 1652, true)
#1 lib/base/dao/dao.class.php(951): baseDAO->sqlError(Object(PDOException))
#2 lib/base/dao/dao.class.php(1104): baseDAO->query('SELECT DISTINCT...')
#3 module/task/tao.php(538): baseDAO->fetchAll('id')
#4 module/task/model.php(1640): taskTao->fetchExecutionTasks(29, 0, 'all', Array, 'storyTitle_asc,...', Object(pager))
#5 module/execution/model.php(2019): taskModel->getExecutionTasks(29, 0, 'all', Array, 'storyTitle_asc,...', Object(pager))
#6 module/execution/control.php(156): executionModel->getTasks(0, 29, Array, 'all', 0, 0, 'storyTitle_asc,...', Object(pager))
#7 framework/base/router.class.php(2479): execution->task(29, 'all', '0', 'storyTitle_asc', '54', '100', '1')
#8 framework/router.class.php(769): baseRouter->loadModule()
#9 www/index.php(88): router->loadModule()
#10 {main}ERROR: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'storyTitle' in order clause is ambiguous ,the sql is: 'SELECT DISTINCT t1.*, t2.id AS storyID, t2.title AS storyTitle, t2.product, t2.branch, t2.version AS latestStoryVersion, t2.status AS storyStatus, IF(t1.`pri` = 0, 256, t1.`pri`) as priOrder FROM `zt_task` AS t1 LEFT JOIN `zt_story` AS t2 ON t1.story = t2.id LEFT JOIN `zt_taskteam` AS t3 ON t3.task = t1.id wHeRe t1.execution = '29' AND t1.deleted = '0' oRdEr bY `storyTitle` asc,`id` asc '
The sql is: SELECT DISTINCT t1.*, t2.id AS storyID, t2.title AS storyTitle, t2.product, t2.branch, t2.version AS latestStoryVersion, t2.status AS storyStatus, IF(t1.`pri` = 0, 256, t1.`pri`) as priOrder FROM `zt_task` AS t1 LEFT JOIN `zt_story` AS t2 ON t1.story = t2.id LEFT JOIN `zt_taskteam` AS t3 ON t3.task = t1.id wHeRe t1.execution = '29' AND t1.deleted = '0' oRdEr bY `storyTitle` asc,`id` asc

in lib/base/dao/dao.class.php on line 1652, last called by lib/base/dao/dao.class.php on line 951 through function sqlError.
in framework/base/router.class.php on line 3221 when visiting /index.php?m=execution&f=task&executionID=29&status=all&param=0&orderBy=storyTitle_asc&recTotal=54&recPerPage=100&zin=1
![WX20240830-185113@2x](https://github.com/user-attachments/assets/4335eae2-4f3f-42ea-8f72-96aab7abfab4)

### 期望 (Expectation)

期望问题可以解决

### 结果 (Result)

期望问题可以解决

### 软件版本 (Software version)

20.4开源版本

**Comment by xiaofeng993229** [comment]
看到你的问题，我做了以下验证，都没有产生和你一样的现象。
1，执行->任务  下点击全部页签，  点击研发需要排序 ，页面可以正常加载。
2，完全复制你提到的sql语句执行，并没有报同样的错误。

你有改动过代码吗？ 还是有特定的重现步骤 ？

另外，可以到 [禅道官网的问答模块](https://www.zentao.net/ask.html) 反馈你遇到的问题，在官网会得到更快的回复。

**Comment by sgm0422** [comment]
你好，在报错文件  module/task/tao.php 中的 fetchExecutionTasks函数加上如图所示的一行代码即可：

`$orderBy = str_replace('storyTitle', 't2.title', $orderBy);`

![image](https://github.com/user-attachments/assets/05a0328b-3301-4942-b42a-fd00cd00270e)

希望可以帮到您

**Comment by sgm0422** [comment]
> 您好，你们有针对此问题做版本修复吗？我这边是docker起的，如果方便我直接拉最新镜像发一下。
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 9/18/2024 11:00 | | To | ***@***.***> | | Cc | ***@***.***>, ***@***.***> | | Subject | Re: [easysoft/zentaopms] ERROR: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'storyTitle' in order clause is ambiguous (Issue #153) | 你好，在报错文件 module/task/tao.php 中的 fetchExecutionTasks函数加上如图所示的一行代码即可： $orderBy = str_replace('storyTitle', 't2.title', $orderBy); image.png (view on web) 希望可以帮到您 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

docker pull easysoft/zentao:20.7-20240918
