### ISSUE TITLE
开源image:18.13与腾讯云mysql安全限制冲突

### ISSUE THREAD

**Issue by cyin888** [easysoft/zentaopms#154]
### 描述 (Description)

使用腾讯云mysql时提示需要super权限，但腾讯云不支持开放super权限，SQLSTATE[42000]: Syntax error or access violation: 1227 Access denied; you need (at least one of) the SUPER privilege(s) for this operation；
<img width="994" alt="image" src="https://github.com/user-attachments/assets/b3df2e6c-a67d-4d0a-a3f2-4bf57026f454">
<img width="1209" alt="image" src="https://github.com/user-attachments/assets/de6923ed-cbdb-4280-a2e7-7e8e80535a48">

### 期望 (Expectation)

云上部署成功

### 结果 (Result)

SQLSTATE[42000]: Syntax error or access violation: 1227 Access denied; you need (at least one of) the SUPER privilege(s) for this operation；

### 软件版本 (Software version)

18.13

**Comment by xiaofeng993229** [comment]
安装时需要使用super权限的数据库用户，没有的话可以在本地安装后将数据库迁移过去；
或者可以试试安装前，注释掉zentao/db/zentao.sql中的 SET global log_bin_trust_function_creators = 1; SET global sql_mode = '';手动进行这两个设置后再进行安装。

另外 ，如果遇到禅道使用问题可以到 [禅道官网 ](https://www.zentao.net/) 的论坛后论坛模块提问，在那里您将获得更及时的回复。

**Comment by sgm0422** [comment]
你好，请问问题解决了么？
首先20版本不会这样报错了，可以体验一下20版本。
其次您的版本的解决办法是：找到禅道目录/db/zentao.sql 文件，将第1、2行sql语句删除，重新执行安装操作即可。
