### ISSUE TITLE
打开测试页面响应慢

### ISSUE THREAD

**Issue by TonyWang8904** [easysoft/zentaopms#155]
### 描述 (Description)

登录后打开测试页面，白屏约20秒后才会出现内容，使用浏览器控制台发现在请求zentao/qa.html?zin=1地址耗费约17秒后返回302，求问如何解决？

### 期望 (Expectation)

页面能够快速打开

### 结果 (Result)

页面打开白屏缓慢

**Comment by xiaofeng993229** [comment]
处理该问题，需要提供更多的信息 ，请添加一好友，我们安排人做排查
请加 QQ 1945249968
或加微信  zentao18563914480

**Comment by xiaofeng993229** [comment]
这块有一个针对内网部署的bug ，如果为内网环境还错误的去请求了互联网的资源。一联系客户单独处理，并记录内部反馈 #7262。
