### ISSUE TITLE
任务列表在按需求排序后，查看任务详情SQL查询出错

### ISSUE THREAD

**Issue by chaosue** [easysoft/zentaopms#156]
### 描述 (Description)

1. 任务列表页，点击 “研发需求”排序:
<img width="852" alt="图片" src="https://github.com/user-attachments/assets/3f8236da-c2f7-4a91-bf05-db0ba3a18b62">
2. 点击任务名称查看详情:
<img width="739" alt="图片" src="https://github.com/user-attachments/assets/bd262c16-6d06-4c0f-a1c1-7b6dc50b8f6d">
3. 任务详情页报错，不能显示:
<img width="1785" alt="图片" src="https://github.com/user-attachments/assets/7505d520-e489-4887-b96f-a815c2f4d4b8">
排序的字段 "storyTitle" 不在查询的字段中。

### 期望 (Expectation)

正确显示任务详情页。

### 结果 (Result)

页面加载失败,出现错误堆栈信息。

### 软件版本 (Software version)

20.8

**Comment by xiaofeng993229** [comment]
感谢您的反馈，已记录，内部反馈编号 7467

**Comment by xiaofeng993229** [comment]
该问题已在 21.1 版本修复。
