### ISSUE TITLE
任务修改实际时间没有效果，还是原来的实际时间

### ISSUE THREAD

**Issue by Sudooomm** [easysoft/zentaopms#157]
### 描述 (Description)

在任务中进行编辑，修改任务的实际开始时间，点击保存后没有生效，还是原来的实际开始时间

### 期望 (Expectation)

希望能够正常修改

### 结果 (Result)

希望能够正常修改

### 软件版本 (Software version)

20.3.0

**Comment by xiaofeng993229** [comment]
该版本存在此问题。 
最新版本已修复，可以考虑升级到最新版本 [ https://www.zentao.net/download/pms20.8-84395.html]( https://www.zentao.net/download/pms20.8-84395.html)   ，升级前需备份。
另外可以到禅道官网交流，在官网你会得到更及时的回复。
