### ISSUE TITLE
文档功能里md部分>符号不能正确被解释？

### ISSUE THREAD

**Issue by matinjugou** [easysoft/zentaopms#16]
在md文档里使用了>符号后会有很多内容消失

**Comment by dajiao007** [comment]
是指在编辑README.MD时，使用了>符号后，此文件有很多内容消失吗。还是其他的情况？能发个截图吗，谢谢。

**Comment by matinjugou** [comment]
对

**Comment by easysoft** [comment]
好的，谢谢反馈。

**Comment by helloMJW** [comment]
同样遇到这个问题, 在编辑文档的时, 两个符号之间的内容全部被删除了。。。。
在 http://www.zentao.net/thread/87384.html 已提.
