### ISSUE TITLE
文档模块中新建文档，图片附件无法显示

### ISSUE THREAD

**Issue by shaobingtongzhi** [easysoft/zentaopms#160]
### 描述 (Description)

我是在demo里试用的，新建了一个测试文档，然后里面传了一个照片，保存后发现图片无法加载
![Snipaste_2024-11-22_17-40-10](https://github.com/user-attachments/assets/a0209f6a-f13c-490d-a681-201f9af290bb)

### 期望 (Expectation)

文档里能看图片

### 结果 (Result)

目前不能看

### 软件版本 (Software version)

开源版 21.0

**Comment by xiaofeng993229** [comment]
demo 站点使用的是21.0版本，确实存在您说的图片不能展示的问题。
该问题已在 最新版21.1 中修复。
您可以通过[ https://www.zentao.net/download/pms21.1-84492.html ]( https://www.zentao.net/download/pms21.1-84492.html )链接下载体验。
