### ISSUE TITLE
使用备份迁移数据后访问域名会显示开源版和修改版本字样

### ISSUE THREAD

**Issue by liuyongqing1** [easysoft/zentaopms#162]
### 描述 (Description)

在从docker环境的备份放到新的机器上 使用一键部署方式恢复相关mysql数据和upload目录后。直接访问相关域名 会跳到初始化页面 ，就是显示开源版本和修改版本的那个位置，如下图。
![image](https://github.com/user-attachments/assets/93a03d47-a023-4b2e-bc7c-f23da9f2ce62)

### 期望 (Expectation)

直接跳转到登陆页面

### 结果 (Result)

目前是初始化页面应该是

### 软件版本 (Software version)

20.1.1

**Comment by xiaofeng993229** [comment]
产生这个问题的原因是：一键安装包安装默认的访问是需要增加 /zentao 的。

可以根据这个文档设置一下，去掉/zentao[https://www.zentao.net/book/zentaopms/131.html]( https://www.zentao.net/book/zentaopms/131.html)

有禅道的使用问题，可以到禅道官网留言，在那里可以得到更快的回复。
