### ISSUE TITLE
20.1.1升级到21.1报错

### ISSUE THREAD

**Issue by liuyongqing1** [easysoft/zentaopms#163]
### 描述 (Description)

在执行Upgrade.php过程中 ,提示如下错误
![image](https://github.com/user-attachments/assets/b7037632-3ebe-4bd1-a650-a0bd0b14c1fa)

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-bug-confirm' for key 'group' ,the sql is: '
UPDATE `zt_grouppriv` SET `method` = 'confirm' WHERE `module` = 'bug' AND `method` = 'confirmBug''
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '8-testcase-batchChangeType' for key 'group' ,the sql is: '
UPDATE `zt_grouppriv` SET `method` = 'batchChangeType' WHERE `module` = 'testcase' AND `method` = 'batchCaseTypeChange''

### 期望 (Expectation)

正常升级

### 结果 (Result)

正常升级

### 软件版本 (Software version)

20.1.1

**Comment by xiaofeng993229** [comment]
我走了一遍  20.1.1 升级到21.1 的流程。 没有出现和你一样的问题。
可能你是重复升级导致的报错（zt_grouppriv 有唯一索引）。
可以参考以下处理方式
1，使用之前的 20.1.1 的数据库备份还原数据库。
2，重新走一遍升级的流程


另外，也可以到禅道官网留言，或添加商务同事的qq，有禅道交流群，在群里可以得到更及时的回复。

**Comment by liuyongqing1** [comment]
我这个版本是从最开始的18.12直接升级到20.1.1 然后准备升级到21版本，但是报上面的错误。
我升级之前有备份原来的数据库，失败后全部删除 重新拷贝过来再次升级也是一样的。

**Comment by xiaofeng993229** [comment]
嗯。加一下qq （1945249968） 吧，远程排查处理一下
