### ISSUE TITLE
git pull origin master 跟新到9.7版本报错： Unknown column 't3.type' in 'where clause 

### ISSUE THREAD

**Issue by leeyisoft** [easysoft/zentaopms#18]
解决方法：
`SET SQL_MODE='ALLOW_INVALID_DATES';
ALTER TABLE `zt_team` ADD `type` enum('project','task') NOT NULL DEFAULT 'project' FIRST;
ALTER TABLE `zt_team` ADD `root` mediumint(8) unsigned NOT NULL default '0' FIRST;

ALTER TABLE `zt_team` DROP PRIMARY KEY;
ALTER TABLE `zt_team` DROP `project`;
ALTER TABLE `zt_team` DROP `task`;
`

错误信息：
`
10:31:53 ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 't3.type' in 'where clause'<p>The sql is: SELECT distinct t1.id FROM `zt_product` AS t1 LEFT JOIN `zt_projectproduct` AS t2 ON t1.id = t2.product LEFT JOIN `zt_team` AS t3 ON t2.project = t3.root LEFT JOIN `zt_project` AS t4 ON t2.project = t4.id wHeRe t1.acl = 'open' OR (t1.acl = 'custom' AND (INSTR(CONCAT(',', t1.whitelist, ','), ',1,') > 0 OR INSTR(CONCAT(',', t1.whitelist, ','), ',6,') > 0 OR INSTR(CONCAT(',', t1.whitelist, ','), ',9,') > 0)) OR t1.PO = 'leeyi' OR t1.QD = 'leeyi' OR t1.RD = 'leeyi' OR t1.createdBy = 'leeyi' OR t3.account = 'leeyi' AND t1.deleted = '0' AND t3.type = 'project' AND t4.deleted = '0'</p> in /var/www/zentaopms/lib/base/dao/dao.class.php on line 1388, last called by /var/www/zentaopms/lib/base/dao/dao.class.php on line 706 through function sqlError.
in /var/www/zentaopms/framework/base/router.class.php on line 2195 when visiting /index.php?m=block&f=printBlock&id=18&module=my

10:31:53 ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'root' in 'field list'<p>The sql is: SELECT root, account FROM `zt_team` wHeRe type = 'project'</p> in /var/www/zentaopms/lib/base/dao/dao.class.php on line 1388, last called by /var/www/zentaopms/lib/base/dao/dao.class.php on line 706 through function sqlError.
in /var/www/zentaopms/framework/base/router.class.php on line 2195 when visiting /index.php?m=block&f=printBlock&id=19&module=my
`

**Comment by easysoft** [comment]
谢谢反馈。:) 我们检查下。

**Comment by wyd621** [comment]
这是新版本的修改，还没有发布。可以到http://www.zentao.net下载9.7的源码包安装。
