### ISSUE TITLE
禅道安全漏洞X2

### ISSUE THREAD

**Issue by sadk** [easysoft/zentaopms#2]
禅道项目管理软件任意文件写入漏洞（需要登录）
http://wooyun.org/bugs/wooyun-2015-0151565
禅道项目管理软件 SQL注入漏洞（无需登录）
http://wooyun.org/bugs/wooyun-2015-0151486

请官方确认一下此漏洞，谢谢！

**Comment by easysoft** [comment]
都已经确认过，谢谢反馈。
