### ISSUE TITLE
Missing the whole English CSS files

### ISSUE THREAD

**Issue by pkostelnik** [easysoft/zentaopms#20]
After git cloninig and setup (which went fine). The site seems to e fully destructed in english in case of missing the en_*****.css file/s within the Theme folders.
`<link rel='stylesheet' href='/theme/default/en.default.css?v=10.0.beta' type='text/css' media='screen' />`

**Comment by easysoft** [comment]
10.0.beta is a beta version not released. The stable version is 9.8 https://github.com/easysoft/zentaopms/releases/tag/zentaopms_9.8_20180118
you can try this version.
