### ISSUE TITLE
请问github的和sourceforge不是同一套代码对吗？

### ISSUE THREAD

**Issue by wymsfot** [easysoft/zentaopms#22]
我以前都是在你们开源官网下载
下载站点1：http://sourceforge.net/projects/zentao/files/9.8.3/ZenTaoPMS.9.8.3.zip/download

今天我fork一个git到本地，和我在用的代码比较后发现差异非常大，两套系统是不同团队在维护开发吗？

**Comment by easysoft** [comment]
github是我们的主库。sf 上面下载的 zip包在打包的时候会生成一些文件。这些文件不在版本库里面。
