### ISSUE TITLE
项目缺少js, css 相关文件

### ISSUE THREAD

**Issue by helloMJW** [easysoft/zentaopms#25]
clone 当前项目到本地运行. 界面混乱.  缺少 all.js zh-cn.default.css 文件. 

![](http://ww1.sinaimg.cn/large/005zIqRggy1fr76np29osj313j0i4wja.jpg)
![](http://ww1.sinaimg.cn/large/005zIqRggy1fr777mfkomj312m0k7djj.jpg)

**Comment by easysoft** [comment]
需要执行make命令，生成。

**Comment by easysoft** [comment]
或者config/my.phpdebug设成true。

**Comment by zhuCheer** [comment]
> 需要执行make命令，生成。

windows下有什么手动执行的方法吗
