### ISSUE TITLE
[建议]修改一下module\upgrade\model.php的checkConsistency方法，第429行

### ISSUE THREAD

**Issue by Xiphin** [easysoft/zentaopms#27]
问题：如果安装的时候修改了表前缀，升级的时候就会报表不一致的提示。

解决：

把
https://github.com/easysoft/zentaopms/blob/83f8947ef734a01982c9b0c7fec94f13978cdd64/module/upgrade/model.php#L429
改成：

```
$table = str_replace('zt_', $this->config->db->prefix, $out[1][0]);
```

**Comment by easysoft** [comment]
谢谢反馈。

**Comment by Xiphin** [comment]
https://github.com/easysoft/zentaopms/commit/7bc823d4902e8de5c80938c2a5fbb165a237e2d2 更新后的代码 这个 $table  = $out[1][0]; 应该删除。

**Comment by easysoft** [comment]
谢谢反馈。已经更正。
