### ISSUE TITLE
客户端中的禅道浏览器无法复制地址

### ISSUE THREAD

**Issue by dust0517** [easysoft/zentaopms#28]
在禅道11.0中提供了一个全新的暄暄作为客户端使用，并且提供了将禅道URL发到聊天窗口中即可转为卡片式消息，但是内置的禅道无法复制地址，也无法通过其他途径获得url，右键在浏览器中打开也没有一键登录功能，也就意味着如果需要发送卡片的话需要单独在浏览器中再次登录，那这样暄暄其实用处就不大了。

**Comment by chenfeiCF** [comment]
您提的这个反馈我们记录需求了，我们内部先讨论下，感谢反馈。

**Comment by chenfeiCF** [comment]
> 在禅道11.0中提供了一个全新的暄暄作为客户端使用，并且提供了将禅道URL发到聊天窗口中即可转为卡片式消息，但是内置的禅道无法复制地址，也无法通过其他途径获得url，右键在浏览器中打开也没有一键登录功能，也就意味着如果需要发送卡片的话需要单独在浏览器中再次登录，那这样暄暄其实用处就不大了。

您提的这个反馈我们记录需求了，我们内部先讨论下，感谢反馈。

**Comment by easysoft** [comment]
我们增加了复制url地址的功能。但打开之后还需要登陆，因为如果可以直接登陆的话，会有安全方面的隐患。
