### ISSUE TITLE
希望增加一个【提需求前扫付款码】的可选功能

### ISSUE THREAD

**Issue by aizhimou** [easysoft/zentaopms#30]
初级版本：提需求前需要扫描收款码支付后才可进入详情编辑页面，收款码可由管理员在后台设置；
高级版本：提需求时不需要付款，指派给某个人时需要扫描收款码，每个人的收款码可由该用户自定义；

**Comment by catouse** [comment]
建议很好啊 😄

**Comment by catouse** [comment]
加个指派任务需要扫描更佳。

**Comment by easysoft** [comment]
:)，这个，哈哈。

**Comment by easysoft** [comment]
这个适合做插件。
