### ISSUE TITLE
OpenId Connect feature reqeust

### ISSUE THREAD

**Issue by yang-xiaodong** [easysoft/zentaopms#32]
Hello, 

OpenId Connect is one of the major authentication protocols used today and one of the first to be used for federated access, giving it a large foothold in the SSO domain, so is there any plan to support it? 

OpenId Connect libs for PHP :  https://github.com/jumbojett/OpenID-Connect-PHP

Thanks,
Savorboard

**Comment by easysoft** [comment]
Thank you for your suggestion. We will study it and decide wether to integrate it or not. Thank  you again.
