### ISSUE TITLE
Able to run without symlinks?

### ISSUE THREAD

**Issue by lukesvec** [easysoft/zentaopms#36]
Olla,
on my hosting cant really use `Options +FollowSymLinks +SymLinksIfOwnerMatch` in htaccess. Its there a way how to use it even without it ?

Seems like all working but thers a file location trouble aka
`(12:57:26 ERROR: 'theme/default/en.default' illegal. in framework/base/router.class.php on line 1287, last called by framework/base/router.class.php on line 1194 through function checkModuleName.
in framework/base/router.class.php on line 2215 when visiting theme/default/en.default)`

edit1. route for file either dont work :/

Can you help me?

**Comment by easysoft** [comment]
How did you install zentao? Just fork the code from github? There's a Makefile. Before we release a version we will run make in shell to merge some css files into a all-in-one file. So there's three ways:
1. Run make under linux to create this file. But you should install some tools.
2. Download our release version from https://www.zentao.pm
3. Change zentao/config/my.php, set debug to 1.

We suggest you to choose way 2.

**Comment by lukesvec** [comment]
just download pack from site. _wanna run in on webhosting(cloud) server to access it from everywhere (not just from local)_.
debug info dont show anything falsed

**Comment by easysoft** [comment]
It's just a error log. If zentao works fine, you can ignore it.

**Comment by lukesvec** [comment]
it doesnt. file wont load due missing file. guess thers is a wrong route for file

**Comment by easysoft** [comment]
You can ask support by the online chat in zentao.pm website.
