### ISSUE TITLE
我在定时器里面增加了自定义参数

### ISSUE THREAD

**Issue by wcj343169893** [easysoft/zentaopms#38]
我在定时器里面增加了自定义参数，还支持post/get请求其他地址，不知道你们是否需要，我也不知道怎么提交代码给你们，这是我的仓库
https://github.com/wcj343169893/zentaopms/commit/f9f2b39b2e0219282c8faac2e421f15ce14315ab

**Comment by easysoft** [comment]
如果局限在禅道内部的定时的话，通过内部的fetch调用就可以了。
你是把它的应用范围扩展到其他的吧，比如可以做监控之类的。
谢谢反馈。代码我就不合并了。如果你感兴趣，可以到我们官网上提交一个插件。
