### ISSUE TITLE
cas support 

### ISSUE THREAD

**Issue by 0312birdzhang** [easysoft/zentaopms#4]
Can you support apereo/cas ?

**Comment by easysoft** [comment]
我们的用户里面用ldap的比较多，用这个的还是第一次听说。

**Comment by 0312birdzhang** [comment]
@easysoft 就是单点登录的，跟ldap不冲突，可以结合使用。发现有sso的模块，但是不支持cas，我个人是搞java的，无能为力做cas的模块 :joy:

**Comment by easysoft** [comment]
sso模块是和我们另外一个产品ranzhi集成用的。:) 禅道的免登录也很简单，最粗暴的方式就是直接在url里面传account=xxx&password=xxxxx。

**Comment by 0312birdzhang** [comment]
@easysoft cas是耶鲁大学好多年前就开始搞的一个中央认证系统，非常完善稳定，用票据跟session等保存登录用户的id。建议禅道可以搞一下，接入比较方便（我改过两个php系统的登录，禅道的讲求模块化，我用粗暴的方式没成功 :cry: )

**Comment by easysoft** [comment]
先了解下，谢谢啦。
