### ISSUE TITLE
Improper handing for getRemoteIp, May cause AccessControl Bypass

### ISSUE THREAD

**Issue by SuperZero** [easysoft/zentaopms#42]
PMS's Global and some Funtion Access Control implemented by getRemoteIp(), but it gets client ip by improper method, an attacker can forge unblocked address to bypass Access Control Strategy.

getRemoteIp() try to get client ip value from `$_SERVER['HTTP_CLIENT_IP']  > $_SERVER["HTTP_X_FORWARDED_FOR"] > $_SERVER["REMOTE_ADDR"]`. But,  `HTTP_CLIENT_IP`，`HTTP_X_FORWARDED_FOR ` extracted from HTTP Request Headers,  attacker can forge a HTTP Request with header like `X-Forwarded-For: 127.0.0.1` to bypass IP Block.
 
this function use in four places:
```
common\model.php // bypass IP white-list to System 
base\router.class.php  // bypass 127.0.0.1 access limitation to detail error-log

//functions below , removed in latest version -.-
editor\control.php // bypass 127.0.0.1 access limitation to editor function
translate\control.php // bypass 127.0.0.1 access limitation to translate function

```
https://github.com/easysoft/zentaopms/blob/e4ce5d1c02b0596482c684a8b3bf85743783c4a2/framework/base/helper.class.php#L602

**Comment by easysoft** [comment]
Thank you. We have changed the logic in the latest version.
