### ISSUE TITLE
Clear Installation instruction for the opensource version

### ISSUE THREAD

**Issue by allamiro** [easysoft/zentaopms#50]
Zentao looks like a great software however without the ability to evaluate the software using the opensource version then may be transition to the paid version  if needed 
Installation instructions require some writing  the read me file

**Comment by reneeteng** [comment]
Thank you for your advice. The installation instruction will be available on Wiki soon.

**Comment by gnovaro** [comment]
Maybe my pull request can help to you

https://github.com/easysoft/zentaopms/pull/51

**Comment by easysoft** [comment]
> 
> 
> Maybe my pull request can help to you
> 
> #51

Thank you for your pr.
