### ISSUE TITLE
Change table type from MyISAM to InnoDB

### ISSUE THREAD

**Issue by gnovaro** [easysoft/zentaopms#53]
This article shows the advantages and some of the reasons why it is worth making the change.
https://kinsta.com/knowledgebase/convert-myisam-to-innodb/

**Comment by easysoft** [comment]
Thank you. We will study it and test zentao with innodb format.

**Comment by gnovaro** [comment]
https://dev.mysql.com/doc/refman/5.6/en/innodb-storage-engine.html#idp78887728

**Comment by easysoft** [comment]
Thank you for your feedback. We have started testing on innodb this sprint.
