### ISSUE TITLE
能否添加安全功能

### ISSUE THREAD

**Issue by loopsoftp** [easysoft/zentaopms#62]
开发组件安全日益重要，大部分漏洞都是针对开发组件而言的，如果可以添加一个组件安全管理功能的话将对很多公司都有帮助

**Comment by easysoft** [comment]
开发组件我们现在默认是禁用了。你有什么更好的建议吗？

**Comment by easysoft** [comment]
你是指做一个内部安全管理的功能模块吧？具体的需求可否说一下？
