### ISSUE TITLE
可否开放Dockerfile，方便大家自定义安装设置？

### ISSUE THREAD

**Issue by xiagw** [easysoft/zentaopms#64]

**Comment by chaiyd** [comment]
https://github.com/chaiyd/zentao.git            我这里有一个

**Comment by xiagw** [comment]
很不错哦，
希望官方可以merg。

还有建议官方 打 tag 和 release 的时候注意设置 latest，
这样可以 用api.github.com 来获取最新版。

**Comment by easysoft** [comment]
谢谢建议。：）
