### ISSUE TITLE
webhook 企业微信群机器人markdown不支持mentioned_mobile_list

### ISSUE THREAD

**Issue by wdongji** [easysoft/zentaopms#75]
企业微信群机器人官网地址：https://work.weixin.qq.com/api/doc/90000/90136/91770；
其中只有文本类型 类型的消息才支持mentioned_mobile_list；是否可以解决一下
module/webhook/model.php中的574行： getWeixinData函数

**Comment by lanzongjun** [comment]
后续会解决一下此类问题，十分感谢您的帮助

**Comment by sy-records** [comment]
Fixed via d4cd0de865eecee4a16950e55217be36897990ce
