### ISSUE TITLE
能更换镜像的默认数据库么？

### ISSUE THREAD

**Issue by rayer4u** [easysoft/zentaopms#76]
现在在使用官方docker镜像，对于当前使用的数据库版本，有不少限制，想更换新的db版本。感觉比较好的做法是使用dockercompose分别启动，但是没有发现相关的dockerfile。能提供下方便修改么？

**Comment by charnet1019** [comment]
+1   这个应该是比较通用的解决方案，希望支持

**Comment by transtone** [comment]
https://github.com/tonynii/zentao_docker-compose

**Comment by lanzongjun** [comment]
> 现在在使用官方docker镜像，对于当前使用的数据库版本，有不少限制，想更换新的db版本。感觉比较好的做法是使用dockercompose分别启动，但是没有发现相关的dockerfile。能提供下方便修改么？

请参考禅道部署之[Docker-compose](https://github.com/tonynii/zentao_docker-compose)
这里提供docker-compose方式部署，将数据库和php分成了两个容器，同时增加了adminer容器可以非常方便的访问和管理数据库
