### ISSUE TITLE
Goodrain开源社区合作申请

### ISSUE THREAD

**Issue by zzzhangqi** [easysoft/zentaopms#78]
您好，我来自开源社区 [Goodrain](https://github.com/goodrain)，我们所运营的开源项目是[Rainbond](https://github.com/goodrain/rainbond)，我们的[官网](https://www.rainbond.com/)

我们有许多用户在使用 **禅道**，因此我们通过 Rainbond 自身的应用市场机制为这些用户提供了一种选择，一键部署生产可用的 **禅道** 集群，这种部署方式很受社区用户的欢迎。所以特此提出一种合作的可能，我们愿意提交一份一键部署 **禅道** 的文档到您的官网文档中，帮助更多同时需要云原生应用管理平台和 **禅道** 的用户了解到这种可能性以及其带来的便利性。

可以参考我们以往与 [Nacos](https://nacos.io/zh-cn/blog/use-nacos-with-rainbond.html)、[Apollo](https://www.apolloconfig.com/#/zh/deployment/third-party-tool-rainbond) 的合作方式。

期待您的答复😚！

**Comment by wwccss** [comment]
好的，谢谢啦。

**Comment by zzzhangqi** [comment]
您可以加我微信呢，`MrSmallQi`

**Comment by zzzhangqi** [comment]
您可以通过邮件 `zhangq@goodrain.com` 联系我
