### ISSUE TITLE
环境变量无效

### ISSUE THREAD

**Issue by qiaofeng1227** [easysoft/zentaopms#79]
https://github.com/easysoft/zentaopms/blob/master/module/install/control.php

即使设置MYSQL_USER,MYSQL_PASSWORD install 页面还是无法生效。无法读取container的环境变量

**Comment by lanzongjun** [comment]
> https://github.com/easysoft/zentaopms/blob/master/module/install/control.php
> 即使设置MYSQL_USER,MYSQL_PASSWORD install 页面还是无法生效。无法读取container的环境变量

请问是如何设置的环境变量，getenv()获取的环境变量与系统的环境变量不一致导致的

**Comment by ironpike** [comment]
16.5/17.0 docker不修改环境变量启动容器，报
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

**Comment by zhouyq** [comment]
安装向导支持环境变量的需求是我们[容器化禅道应用](https://github.com/quicklyon/zentao-docker)时提出的，如果是非容器内使用该特性，需要系统和PHP环境同时支持才行：

1、系统

要确保 `MYSQL_USER`、`MYSQL_PASSWORD`、`MYSQL_DB`、 `MYSQL_HOST` 、`MYSQL_PORT` 这些环境变量是系统级生效的，可以写在系统的初始化配置中如：/etc/profile 或 /etc/bash.bashrc 

2、PHP环境
如果使用的是php-fpm，请确保php-fpm.conf 的配置文件，如 /etc/php/php-fpm.d/www.conf  中设置  `clear_env = no`
如果使用 apache 请确保启动apache之前 执行 `env | grep MYSQL_` 看看mysql的环境变量是否生效。

**Comment by zhouyq** [comment]
> https://github.com/easysoft/zentaopms/blob/master/module/install/control.php
> 
> 即使设置MYSQL_USER,MYSQL_PASSWORD install 页面还是无法生效。无法读取container的环境变量

如果是容器内使用，请参考 https://github.com/quicklyon/zentao-docker
