### ISSUE TITLE
directory permission

### ISSUE THREAD

**Issue by netcrop** [easysoft/zentaopms#80]
During the fresh install of zentao 16.5 a warning shows up:
" A tmp directory cannot be created. Make sure the directory zentaoalm/www/data exists and you have the right permission Command:
chmod o=rwx -R zentaoalm/www/data"
Why this directory and all files within requires "o=rwx" permission? if this is a upload directory, then what is the purpose of zentaoalm/www/data/upload ?

**Comment by wwccss** [comment]
The attatchment files need be uploaded to this directory, so requires o=rwx

**Comment by netcrop** [comment]
I see, only directory zentaoalm/www/data/upload needs o=rwx permissions, not zentaoalm/www/data/. because there are *.js files within it and it's not safe to have *.js files with o=rwx permissions. Am I right?

**Comment by lanzongjun** [comment]
You are right, but there is no zentaoalm/www/data/upload directory during the fresh install of zentao, so give zentaoalm/www/data directory permission

**Comment by netcrop** [comment]
Thanks! I will install the new version with this permissive permission and change it to a more restrictive permission afterwards.
