### ISSUE TITLE
ztf推送到禅道，列表看不到测试单，动态能看到（禅道微信群建议提报）

### ISSUE THREAD

**Issue by wendy1901** [easysoft/zentaopms#81]
![image](https://user-images.githubusercontent.com/31026667/173332494-f0daf44d-64d1-4185-8c36-f71447ecfcbd.png)
![image](https://user-images.githubusercontent.com/31026667/173332508-f9e6c592-f677-408b-8345-1403840da7f7.png)
![image](https://user-images.githubusercontent.com/31026667/173332533-1611feae-2a05-425a-a644-deb125c7ee44.png)

**Comment by aaronchen2k** [comment]
已解决，老的禅道版本请参照以下文章安装插件。
https://ztf.im/book/ztf/zentao-compatibility-169.html
