### ISSUE TITLE
ZTF推送禅道，报错（禅道微信群建议提报问题）

### ISSUE THREAD

**Issue by wendy1901** [easysoft/zentaopms#82]
![ce9d6bb8b880c6375aeab2b45a44933](https://user-images.githubusercontent.com/31026667/173332824-c3bfdaa6-2324-40e6-882d-e8645ee1b96d.png)

![51ae24fe9607d7122a9788bb702b079](https://user-images.githubusercontent.com/31026667/173332680-2785bd2c-a760-42cb-a466-1f4b488457b2.png)
 网页访问能正常访问
![551baadc17e554f201d70f2eaa9fd1f](https://user-images.githubusercontent.com/31026667/173332731-cf8ba72d-add2-4450-a2a2-a44c46b12392.png)
![3681f06c539022089eeb9f379115592](https://user-images.githubusercontent.com/31026667/173332893-036e26a9-71d8-4ec5-852e-f13110ae8d29.png)
登录失败，禅道返回：invalid character '<' looking for beginning of value。

**Comment by wendy1901** [comment]
执行这个命令报错  ztf.exe co -product 2 -language python  --verbose

**Comment by aaronchen2k** [comment]
已解决，老的禅道版本请参照以下文章安装插件。
https://ztf.im/book/ztf/zentao-compatibility-169.html
