### ISSUE TITLE
安装完成登录后页面没有内容浏览器报错

### ISSUE THREAD

**Issue by yenaikafei** [easysoft/zentaopms#85]
Refused to apply style from 'http://10.137.5.75:8081/theme/default/en.default.css?v=17.2' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
10.137.5.75/:1 Refused to execute script from 'http://10.137.5.75:8081/js/all.js?v=17.2' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
(index):263 Uncaught ReferenceError: $ is not defined
    at (index):263:9
    at (index):952:2
10.137.5.75/:1 Refused to apply style from 'http://10.137.5.75:8081/theme/default/en.default.css?v=17.2' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by wwccss** [comment]
strict MIME checking is enabled.

Please check your config of webserver, apache or nignx and turn off this featurn off and restart the webserver.

**Comment by yenaikafei** [comment]
> 

how to turn off the strict MIME checking? I haven't found a way to turn off this feature

**Comment by wwccss** [comment]
https://stackoverflow.com/questions/39228657/disable-chrome-strict-mime-type-checking perhaps you can check this。
