### ISSUE TITLE
用户项目权限

### ISSUE THREAD

**Issue by everpan** [easysoft/zentaopms#89]
新建普通用户，只有”地盘“
即使项目权限分组中，加入用户，也没法拥有权限
user->model->authorize 这里的权限逻辑存在问题
1082 行 ->andWhere('t1.project')->eq(0)，导致用户拥有的项目proj_id=1的权限丢失
--
即使去除此行，仍然导致 m=project&f=index等没法访问。
望排查下这里的权限合并逻辑

**Comment by lanzongjun** [comment]
新加入的用户还需要加入项目的相关权限后才可以进行项目的相关操作和查看

**Comment by lanzongjun** [comment]
项目管理员权限分组，只控制项目里面的操作。
项目一级导航，项目列表看板之类的，还是视野和系统权限控制的。
