### ISSUE TITLE
选择相关需求，改变评审状态 不生效

### ISSUE THREAD

**Issue by everpan** [easysoft/zentaopms#95]
![image](https://user-images.githubusercontent.com/3960446/195387628-0eb834c7-8a61-4a9d-8b1a-7da8572823ce.png)
![image](https://user-images.githubusercontent.com/3960446/195387950-8c5b1a65-018d-4f9b-a2d9-ea82d883a423.png)
assignedTo 传递丢失

**Comment by lanzongjun** [comment]
指派的行为操作不在评审的时候进行修改
