### ISSUE TITLE
执行(已经选中)->新建任务->所属执行为空白

### ISSUE THREAD

**Issue by everpan** [easysoft/zentaopms#96]
![image](https://user-images.githubusercontent.com/3960446/195741808-015d3adf-b554-451b-9bfe-c646e5f950dc.png)
在选中的情况下应该显示“所属执行”，并不可修改

**Comment by xiaofeng993229** [comment]
禅道18系列，及20系列。通过执行->新建任务 入口去创建任务的话，所属执行是不为空的。但是这里的所属执行拉下还是可以修改的（主要是为了方便快速的创建其他执行下的任务）
![image](https://github.com/easysoft/zentaopms/assets/7753756/9cd958e7-ad97-441b-af6d-79e5cd8d548a)
