### ISSUE TITLE
BUG数量多，万条；新建bug异常缓慢

### ISSUE THREAD

**Issue by everpan** [easysoft/zentaopms#97]

**Comment by binary5** [comment]
请问后来怎么样了？有好的解决方法吗？

**Comment by xiaofeng993229** [comment]
bug数量多不是页面加载缓慢的原因，应该是加载关联需求和关联用例时导致的。
新版的禅道对这块的性能有了优化（上万条需求，上万条用例加载到创建bug页面也非常快），可以考虑升级到18.7 或之后版本 。
