### ISSUE TITLE
禅道无法登录

### ISSUE THREAD

**Issue by jiuaige** [easysoft/zentaopms#98]
周末服务器断电，周一开工后重启zentao服务
页面无法登录，日志提示ERROR] mariadbd: Table './zentao/zt_config' is marked as crashed and should be repaired
按百度repair后还是无法登录，日志无反应，求助大神

**Comment by xia0ta0** [comment]
这个问题是mariadb的数据库文件损坏，只能通过修复数据表进行解决。除了在mysql控制台进行repair外，可以试试mysqlcheck命令。
如果有备份的话，新建一个数据库，导入备份数据。将生成的zt_config表文件覆盖试试，注意做好备份。
