### ISSUE TITLE
升级到17后API创建用户不能加上权限

### ISSUE THREAD

**Issue by 775838893** [easysoft/zentaopms#99]
之前的版本，加权限只需要传字段group和对应的id值即可，现在升级到17后，这个方式不行了，创建用户没有权限，是哪里修改了吗

**Comment by 775838893** [comment]
之前的版本是传group=对应的组id即可，现在看源码是要传一个逗号分隔的数组还是什么？有示例吗
![image](https://user-images.githubusercontent.com/7666283/197675065-5924df50-7aee-4d21-a72e-2cecd3f0b4b8.png)

**Comment by sy-records** [comment]
一样的，传入对应的权限编号即可，多个使用`,`进行分隔。

```json
{"account": "usertest", "password": "123qwe!@#", "realname": "测试用户", "group" : "1,5"}
```
